### ISSUE TITLE
Ctrl+D hides all non-ATIS entries

### ISSUE THREAD

**Issue by laxentis** [kengreim/mini-metars#5]
My understanding is that Ctrl+D should hide the input box and the delete icons, instead all lines with no ATIS code letter are hidden as well.

Before pressing Ctrl+D:
![obraz](https://github.com/user-attachments/assets/578766a2-2f9d-4b36-943e-18c3f69d7e7b)
After pressing:
![obraz](https://github.com/user-attachments/assets/18d39b5e-a354-44b3-a69a-683ef35be45e)

**Comment by kengreim** [comment]
Are you using the latest builds from Releases? That's odd -- I wrote some code in a branch yesterday that provides the behavior you see (as an FR from one of our controllers), but a) it should default to **not** doing this and b) it just lives in its own branch right now.

**Comment by laxentis** [comment]
I've used the latest release version for Windows by using the `Mini.METARs_0.0.3_x64_en-US.msi` installer.

**Comment by kengreim** [comment]
Interesting, ok. I used Github Actions to build the separate branch as a test yesterday and I think it overwrote the previous release somehow.

Can you post your profile JSON if you have one saved?

**Comment by laxentis** [comment]
[EPWW.json](https://github.com/user-attachments/files/16648375/EPWW.json)
I see it has the `"hideAirportIfMissingAtis": true` line.

**Comment by kengreim** [comment]
Thanks. Yep, that confirms that my build yesterday accidentally overwrote the release somehow. And I originally had it as `showAirportIfMissingAtis` so I set it to `true` as the default. I changed the name and the logic to match but forgot to change the default.

I'll have a new build posted as a v0.0.4 in the next hour

**Comment by kengreim** [comment]
Posted -- let me know if you have any issues.

https://github.com/kengreim/mini-metars/releases/tag/release-v0.0.4

**Comment by laxentis** [comment]
Now works as expected.
I would suggest adding a keyboard shortcut or other way of setting the `showAirportIfMissingAtis` option via the UI.

**Comment by kengreim** [comment]
> Now works as expected. I would suggest adding a keyboard shortcut or other way of setting the `showAirportIfMissingAtis` option via the UI.

Done in v0.0.5 with Ctrl + H
